PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE doctrine_migration_versions (version VARCHAR(191) NOT NULL, executed_at DATETIME DEFAULT NULL, execution_time INTEGER DEFAULT NULL, PRIMARY KEY(version));
INSERT INTO doctrine_migration_versions VALUES('DoctrineMigrations\Version20230502145224','2023-05-02 14:54:58',8);
INSERT INTO doctrine_migration_versions VALUES('DoctrineMigrations\Version20230503121750','2023-05-03 12:18:42',5);
INSERT INTO doctrine_migration_versions VALUES('DoctrineMigrations\Version20230523095236','2023-05-23 09:58:41',3);
INSERT INTO doctrine_migration_versions VALUES('DoctrineMigrations\Version20230523103440','2023-05-23 10:45:12',3);
INSERT INTO doctrine_migration_versions VALUES('DoctrineMigrations\Version20230524072718','2023-05-24 07:27:26',5);
INSERT INTO doctrine_migration_versions VALUES('DoctrineMigrations\Version20230524073043','2023-05-24 07:30:45',4);
INSERT INTO doctrine_migration_versions VALUES('DoctrineMigrations\Version20230524092749','2023-05-24 09:30:24',3);
INSERT INTO doctrine_migration_versions VALUES('DoctrineMigrations\Version20230524103814','2023-05-24 10:38:18',4);
INSERT INTO doctrine_migration_versions VALUES('DoctrineMigrations\Version20230525081214','2023-05-25 08:12:22',4);
INSERT INTO doctrine_migration_versions VALUES('DoctrineMigrations\Version20230525084854','2023-05-25 08:48:58',4);
CREATE TABLE messenger_messages (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, body CLOB NOT NULL, headers CLOB NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at DATETIME NOT NULL, available_at DATETIME NOT NULL, delivered_at DATETIME DEFAULT NULL);
CREATE TABLE book (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, title VARCHAR(255) NOT NULL, isbn VARCHAR(255) NOT NULL, author VARCHAR(255) NOT NULL, image VARCHAR(255) DEFAULT NULL);
INSERT INTO book VALUES(1,'Den påhittade boken','1904189346767','Anders Andersson','https://parenting.mountsinai.org/wp-content/uploads/2018/02/a9af58bd53e74b13de6a7f44b70fd0aa.jpg');
INSERT INTO book VALUES(2,'The Imaginary','9103981976961','A.F. Harrold','https://images.squarespace-cdn.com/content/v1/54ae789de4b04c0d6f5e6241/1594198620812-9BS2CYMT74XXGYOHO8IS/THE+IMAGINARY+PB.jpg');
INSERT INTO book VALUES(4,'Harry Potter och de vises sten','9789129723946','J.K. Rowling','https://s2.adlibris.com/images/54131168/harry-potter-och-de-vises-sten.jpg');
INSERT INTO book VALUES(5,'Harry Potter och hemligheternas kammare','9789129723960','J.K. Rowling','https://s1.adlibris.com/images/54131167/harry-potter-och-hemligheternas-kammare.jpg');
INSERT INTO book VALUES(8,'Harry Potter och fången från Azkaban','9789129723953','J.K. Rowling','https://s1.adlibris.com/images/54131432/harry-potter-och-fangen-fran-azkaban.jpg');
INSERT INTO book VALUES(9,'Harry Potter och den flammande bägaren','9789129723915','J.K. Rowling','https://s2.adlibris.com/images/52385780/harry-potter-och-den-flammande-bagaren.jpg');
CREATE TABLE rooms (room_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, room_name VARCHAR(255) NOT NULL, description CLOB NOT NULL, north INTEGER DEFAULT NULL, east INTEGER DEFAULT NULL, south INTEGER DEFAULT NULL, west INTEGER DEFAULT NULL, image VARCHAR(255) DEFAULT NULL, n_lock VARCHAR(255) DEFAULT NULL, e_lock VARCHAR(255) DEFAULT NULL, s_lock VARCHAR(255) DEFAULT NULL, w_lock VARCHAR(255) DEFAULT NULL);
INSERT INTO rooms VALUES(1,'Stugan','Du vaknar upp i en mörk och kuslig stuga. Du ser en dörr i nordlig riktning som otroligt nog verkar vara öppen. I stugan ser du också en stor bultsax och en flaska med okänt innehåll.',2,NULL,NULL,NULL,'img/rum1.png',NULL,NULL,NULL,NULL);
INSERT INTO rooms VALUES(2,'Trädgården','Du hamnar i en mörk trädgård. Det verkar vara ett högt staket runt hela trädgården och omöjligt att ta sig igenom åt alla håll, förutom öst där det finns en stor grind eller tillbaka till stugan. Grinden är låst med en grov kedja och omöjlig att klättra över. I trädgården ser du även en spade och en trädgårdstomte där någonting glänser till under den.',NULL,3,1,NULL,'img/rum2.png',NULL,'Bultsax',NULL,NULL);
INSERT INTO rooms VALUES(3,'Gläntan','Efter att ha tagit dig igenom grinden hamnar du i en skogsglänta. Framför dig finns en skattkista som är låst. Du ser ut att behöva en nyckel för att öppna den.',NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,NULL);
CREATE TABLE items (item_id VARCHAR(255) NOT NULL, item_name VARCHAR(255) NOT NULL, description CLOB NOT NULL, use_desc CLOB NOT NULL, room_id INTEGER NOT NULL, grab VARCHAR(255), lift VARCHAR(255), hidden_under VARCHAR(255) DEFAULT NULL, usable VARCHAR(255) DEFAULT NULL, locked VARCHAR(255) DEFAULT NULL, PRIMARY KEY(item_id));
INSERT INTO items VALUES('bultsax1','Bultsax','En bultsax','Du använder bultsaxen för att klippa upp hänglåset',1,'yes',NULL,NULL,NULL,NULL);
INSERT INTO items VALUES('flaska1','Flaska','En flaska med en grönaktig vätska i','Du dricker innehållet och mår lite illa. Varför gjorde du så?',1,'yes',NULL,NULL,'yes',NULL);
INSERT INTO items VALUES('nyckel1','Nyckel','En nyckel','Du låser upp kistan',2,'no',NULL,'gnome1',NULL,NULL);
INSERT INTO items VALUES('gnome1','Trädgårdstomte','En trädgårdstomte','inget',2,NULL,'yes',NULL,NULL,NULL);
INSERT INTO items VALUES('spade1','Spade','En spade','Spaden är helt värdelös',2,'yes',NULL,NULL,'yes',NULL);
INSERT INTO items VALUES('kista1','Kista','En skattkista som är låst','inget',3,NULL,NULL,NULL,NULL,'Nyckel');
INSERT INTO items VALUES('inget','Ingenting','Det här är ingenting','Ingenting händer',0,NULL,NULL,NULL,NULL,NULL);
DELETE FROM sqlite_sequence;
INSERT INTO sqlite_sequence VALUES('book',260);
INSERT INTO sqlite_sequence VALUES('rooms',192);
CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name);
CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at);
CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at);
COMMIT;
