<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBcfuvyy\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBcfuvyy/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerBcfuvyy.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerBcfuvyy\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerBcfuvyy\App_KernelTestDebugContainer([
    'container.build_hash' => 'Bcfuvyy',
    'container.build_id' => '62a33565',
    'container.build_time' => 1683815632,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBcfuvyy');
